--- #YAML:1.0
name: XML-RSS-Tools
version: 0.20
abstract: A tool-kit providing a wrapper around a HTTP client, a RSS parser, and a XSLT engine.
author:
  - Adam Trickett <atrickett@cpan.org>
license: gpl
distribution_type: module
requires:
  LWP: 5.7
  URI: 1.31
  XML::LibXML: 1.5
  XML::LibXSLT: 1.5
  XML::RSS: 1
  perl: 5.6.1
recommends:
  HTTP::GHTTP: 1
  HTTP::Lite: 2.1
  Test::Pod: 0
  Test::More: 0
  IO::Capture: 0
build_requires:
  Sys::Hostname: 0
  IO::Socket: 0
  Test: 0
  Test::More: 0
provides:
  XML::RSS::Tools:
    file: lib/XML/RSS/Tools.pm
    version: 0.20
meta-spec:
   version: 1.3
   url: http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: Hand 1.0
