# $Id: META.yml 67 2008-06-29 14:17:37Z adam $
--- #YAML:1.0
name: XML-RSS-Tools
version: 0.30
abstract: A tool-kit providing a wrapper around a HTTP client, a RSS parser, and a XSLT engine.
author:
  - Adam Trickett <atrickett@cpan.org>
license: gpl
distribution_type: module
requires:
  LWP: 5.8
  URI: 1.35
  XML::LibXML: 1.59
  XML::LibXSLT: 1.59
  XML::RSS: 1.22
  perl: 5.6.1
recommends:
  HTTP::GHTTP: 1
  HTTP::Lite: 2.1
  WWW::Curl::Easy: 4
build_requires:
  Pod::Coverage: 0.18
  URI::file: 4.19
  Test::Pod: 1.0
  Test::Warn: 0.09
  Test::NoWarnings: 0.83
  IO::Capture: 0.04
provides:
  XML::RSS::Tools:
    file: lib/XML/RSS/Tools.pm
    version: 0.30
resources:
  homepage: http://www.iredale.net/p/by-permalink/45203A44-EACB-11DC-9A07-61EB6225452B/
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=XML-RSS-Tools
meta-spec:
   version: 1.3
   url: http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: Hand 1.0
