# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-RSS-Tools
version:      0.13_5
version_from: Tools.pm
installdirs:  site
requires:
    LWP:                           5.6
    URI:                           1.21
    XML::LibXML:                   1.5
    XML::LibXSLT:                  1.5
    XML::RSS:                      1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.15
